Repository Programmiermethoden-CampusMinden/Deploy-to-Grading, pull requests merged in 2023-07, with the labels that each got.

#57 [Documentation] Fix bott2017 url
  doc/related_work/book/bott2017.md
Labels: bug, documentation

#64 CODEOWNERS: add scripts folder
  .github/CODEOWNERS
Labels: bug

#59 [D2G] Metrik Kompilieren hinzugefügt
  scripts/metrics/compile.sh
  scripts/metrics/compile_eval.py
Labels: staff:wimi

#63 [D2G] Metrik JUnit Unittests hinzugefügt
  scripts/metrics/junit.sh
  scripts/metrics/junit_eval.py
Labels: staff:wimi

#51 [D2G] checkout_due_date-Skript hinzugefügt
  scripts/checkout_due_date.sh
Labels: staff:wimi

#62 [D2G] Evaluate-Task-Skript hinzugefügt
  scripts/evaluate_task.py
Labels: staff:wimi

#70 [D2G] Rahmenskript für das Deploy-to-Grading
  .gitignore
  scripts/checkout_due_date.sh
  scripts/deploy_to_grading.py
  scripts/evaluate_task.py
  scripts/load_yaml.py
  scripts/metrics/compile_eval.py
  scripts/metrics/junit.sh
  scripts/metrics/junit_eval.py
  scripts/override_repo.py
Labels: staff:wimi

#74 [D2G] Typos gefixt
  scripts/checkout_due_date.sh
  scripts/deploy_to_grading.py
  scripts/load_yaml.py
  scripts/metrics/compile_eval.py
Labels: staff:wimi, bug

#76 [D2G] create_artifact.sh hinzugefügt
  scripts/create_artifact.sh
  scripts/deploy_to_grading.py
Labels: staff:wimi

#73 [D2G] Metrik Codeformat hinzugefügt
  scripts/metrics/codeformat.sh
  scripts/metrics/codeformat_eval.py
Labels: staff:wimi

#72 [D2G] Metrik Javadoc hinzugefügt
  scripts/metrics/javadoc.sh
  scripts/metrics/javadoc_eval.py
Labels: staff:wimi

#81 Editorconfig: Ergänze Einträge für Gradle
  .editorconfig
Labels: bug
